language: node_js
node_js:
- node
before_script:
- npm run build
script:
- npm test
install:
- npm install
deploy:
  provider: pages
  skip-cleanup: true
  github-token: process.env.GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: gh-pages